import LegalDocument, { type LegalSection } from "@/components/LegalDocument";
import { COMPANY } from "@/lib/company";

const sections: LegalSection[] = [
  { id: "who-we-are", title: "Who we are", content: <p>{COMPANY.name} is based in {COMPANY.locality}. This policy explains how we handle information when you use this website, request a quotation, or discuss travel arrangements with our team.</p> },
  { id: "information", title: "Information you share", content: <><p>Our enquiry forms collect your name, phone number, departure city, journey preference, selected package and airline, batch or preferred departure date, traveller count, and your message. Package pricing and room-sharing details may also be recorded with your request.</p><p>You may provide an email address or further information through calls, email, WhatsApp, or a booking discussion. For an initial enquiry, share only what is needed. Please do not upload passport scans, payment card details, or medical documents through the general enquiry form.</p><p>When a booking requires passport, visa, insurance, or accessibility information, we will explain the purpose and the appropriate way to provide it.</p></> },
  { id: "purpose", title: "How we use information", content: <><ul><li>Respond to your enquiry and prepare relevant package options and quotations.</li><li>Discuss departure dates, room sharing, flights, and group requirements.</li><li>Coordinate requested bookings, documents, and travel updates.</li><li>Handle questions, complaints, and necessary business records.</li><li>Maintain website security and meet applicable legal obligations.</li></ul><p>Submitting a form asks us to contact you about that request. It does not automatically subscribe you to unrelated promotional messages. You can ask us to stop promotional contact at any time.</p></> },
  { id: "providers", title: "Service providers and sharing", content: <><p>Website enquiries are stored using Supabase, with access restricted to authorised administrators. Our hosting and communication providers also process information needed to operate their services.</p><p>For arrangements you request, relevant information may be shared with airlines, hotels, transport operators, visa or insurance providers, and booking partners. International travel can require information to be processed outside India, including in Saudi Arabia. We may also disclose information where required by law or to address fraud or security concerns.</p><p>We do not sell enquiry information. Clicking a WhatsApp, map, airline, or other external link takes you to a service governed by its own privacy terms.</p></> },
  { id: "storage", title: "Browser storage and technical information", content: <><p>The site uses browser storage to remember a dismissed enquiry popup. Administrator sign-in, listing drafts, and navigation preferences use local or session storage. Hosting services may process technical logs, such as IP addresses and browser information, to deliver and protect the website.</p><p>You can clear storage or limit it in your browser settings; this may reset preferences or affect administrator sign-in. If optional analytics or advertising tools are introduced, this policy and any necessary preference controls will be updated.</p></> },
  { id: "security", title: "Security and retention", content: <><p>Website connections use HTTPS in production, and database access is restricted by authentication and access policies. No online system can guarantee absolute security.</p><p>We retain enquiry information while handling your request and related follow-up. Booking, payment, and complaint records may need to be retained for applicable accounting, legal, or dispute requirements. Contact us to request deletion of information that is no longer needed; we will explain any lawful reason for retaining it.</p></> },
  { id: "requests", title: "Your choices and privacy requests", content: <><p>You can contact us to ask about your information, correct inaccurate details, request deletion, withdraw a consent you have given, or raise a privacy concern. We will assess the request under applicable law and may need proportionate information to verify your identity.</p><p>Send requests to <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> with the subject “Privacy request”. Avoid sending identity documents unless our team requests them through an appropriate channel. Withdrawing consent may affect arrangements that require the information.</p></> },
  { id: "children", title: "Children and group enquiries", content: <p>Enquiries should be submitted by an adult. A parent, guardian, or authorised group organiser may give traveller counts and relevant requirements for children. Do not include unnecessary identifying details about children in the enquiry message. Further child traveller information should be provided only when required for a booking and with the appropriate authority.</p> },
  { id: "updates", title: "Policy updates and concerns", content: <p>We may update this policy as our services or applicable requirements change. The date at the top identifies the current version. For questions or unresolved concerns, contact the travel team using the details below, describing your request and the best way to reach you.</p> },
];

export default function Privacy() {
  return <LegalDocument title="Privacy Policy" description="How we handle your travel enquiry, personal information, and privacy requests." sections={sections} />;
}
