import LegalDocument, { type LegalSection } from "@/components/LegalDocument";
import { COMPANY } from "@/lib/company";

const sections: LegalSection[] = [
  { id: "company", title: "About these terms", content: <><p>These terms apply to the {COMPANY.name} website and enquiries about Umrah, Hajj, and related travel services. Our office is in {COMPANY.locality}; the full address and contact details appear below.</p><p>An enquiry or selected package is a request for information, not a confirmed booking. Before paying, review the written quotation, itinerary, responsible providers, payment schedule, and the booking-specific terms supplied to you.</p></> },
  { id: "prices", title: "Packages and indicative prices", content: <><p>Displayed prices are in Indian rupees and are indicative unless a written quotation states otherwise. A “per adult” price applies to the stated sharing basis, such as 4/5 Sharing. Children, infants, different room occupancy, upgrades, taxes, and additional services may have separate charges.</p><p>Traveller totals may include children and infants. An adult subtotal does not represent the final group price. Senior travellers are included in the adult count. Batch dates, fares, hotels, and availability must be confirmed before booking; prices can change before confirmation.</p></> },
  { id: "confirmation", title: "Quotations, payments and confirmation", content: <><p>A quotation should identify the selected flight option, dates, room-sharing basis, itinerary, inclusions, exclusions, total payable, validity period, and payment recipient. Confirm any unclear detail before payment.</p><p>Pay only using the method and recipient confirmed by our team and retain your receipt. A booking is confirmed only when you receive written confirmation and the stated confirmation conditions are met. Submitting this website form creates no payment obligation.</p></> },
  { id: "flights-hotels", title: "Flights, accommodation and services", content: <><p>The confirmed itinerary sets out airline routing, baggage allowances, hotels, meals, transfers, and other included services. Airline and hotel terms may also apply. Hotel distances shown in a package are approximate and depend on the confirmed property and walking route.</p><p>Airline schedules and operational arrangements can change. Any necessary change or proposed substitute should be communicated with its effect on your itinerary and applicable charges. Logos and destination images help illustrate travel options and do not themselves establish a commercial partnership.</p></> },
  { id: "documents", title: "Passports, visas and Hajj arrangements", content: <><p>Travellers must check current passport, visa, health, entry, and transit requirements for their nationality and itinerary. Provide accurate names and documents that match the booking. Tell the team promptly about any discrepancy.</p><p>Visa and permit decisions belong to the relevant authorities. Assistance does not guarantee approval. Hajj enquiries depend on official eligibility, quota, permits, and authorised arrangements; availability and the responsible booking route must be verified for the relevant season.</p></> },
  { id: "changes", title: "Changes, cancellation and refunds", content: <><p>Before paying, request the cancellation, amendment, no-show, and refund terms for your booking. Charges can depend on when you cancel, ticket conditions, hotel commitments, and other provider rules. No universal refund percentage or processing time applies to all packages.</p><p>Send change or cancellation requests to our team in writing. We will confirm receipt, explain applicable charges and refundable amounts, and provide the expected processing position. Refund handling remains subject to applicable consumer law and does not remove rights that cannot lawfully be excluded.</p></> },
  { id: "needs", title: "Traveller needs and responsibilities", content: <><p>An adult should submit enquiries and have authority to discuss requirements for other travellers in their group. Raise mobility, accessibility, dietary, room-sharing, child, and senior traveller needs before booking so suitability can be assessed.</p><p>Review your documents and itinerary, follow official instructions and local rules, and arrive in time for flights and transfers. Discuss suitable travel insurance and check its coverage, exclusions, and claims process before departure.</p></> },
  { id: "disruption", title: "Disruption and service concerns", content: <><p>Weather, airline disruption, official decisions, public health restrictions, and other events outside a provider's reasonable control can affect travel. The applicable booking and provider terms determine available options; we will help you understand the arrangements and next steps.</p><p>Report service issues promptly, keeping relevant receipts and correspondence. Provider responsibilities and any lawful limitations must be stated in the confirmed booking. These website terms do not exclude liability or statutory rights that cannot lawfully be excluded.</p></> },
  { id: "website", title: "Website use and content", content: <p>Use the website for legitimate enquiries. Do not submit false information, attempt unauthorised administrator access, or interfere with the site. Branding, text, images, and airline or hotel marks belong to their respective owners. General travel information is a planning aid; your confirmed booking documents determine the services purchased.</p> },
  { id: "privacy", title: "Personal information", content: <p>Our <a href="/privacy">Privacy Policy</a> explains how enquiry and booking information is handled. The initial form is for travel preferences; do not send payment card details, passport scans, or unnecessary sensitive information through it.</p> },
  { id: "law", title: "Applicable law and resolving questions", content: <p>These website terms are governed by applicable Indian law. Please contact our team first with a booking or website concern so it can be investigated. Disputes may be raised before the competent courts, consumer forums, or other authorities with jurisdiction; nothing here restricts an available statutory remedy.</p> },
  { id: "updates", title: "Updates to these terms", content: <p>Updates will be published here with a revised date. A later website update does not, by itself, change an existing confirmed booking. Refer to the terms agreed for that booking and any subsequent changes accepted by the parties.</p> },
];

export default function Terms() {
  return <LegalDocument title="Terms & Conditions" description="Clear terms for package enquiries, booking confirmation, payments, changes, and traveller responsibilities." sections={sections} />;
}
