"use client";
import { useEffect, useRef, useState } from "react";
import { Plus, Pencil, Trash2, Upload, Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { z } from "zod";
import { readAdminStorage, writeAdminStorage } from "@/lib/admin-workspace";
import { getSupabaseClient } from "@/integrations/supabase/client";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { flightSchema, slugify, type CmsCategory, type CmsPackage, type FlightOption } from "@/lib/travel-cms";
const field="w-full min-w-0 rounded-xl border border-black/15 bg-white px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-black/20";
const emptyCategory={name:'',slug:'',description:'',image_url:'',image_alt:'',sort_order:0,published:false};
const emptyPackage={name:'',slug:'',category_id:'',description:'',image_url:'',image_alt:'',destinations:'Makkah & Madinah',departure_city:'Bangalore',duration_days:'' as string|number,sharing:'4/5 Sharing',hotel_details:'',inclusions:'',exclusions:'',itinerary:'',terms:'Availability and final price confirmed before booking.',featured:false,published:false,sort_order:0};
const categoryDraftSchema=z.object({name:z.string(),slug:z.string(),description:z.string(),image_url:z.string(),image_alt:z.string(),sort_order:z.number(),published:z.boolean()});
const packageDraftSchema=categoryDraftSchema.extend({category_id:z.string(),destinations:z.string(),departure_city:z.string(),duration_days:z.union([z.string(),z.number()]),sharing:z.string(),hotel_details:z.string(),inclusions:z.string(),exclusions:z.string(),itinerary:z.string(),terms:z.string(),featured:z.boolean()});
const draftSchema=z.object({kind:z.enum(['packages','categories']),id:z.string().nullable(),category:categoryDraftSchema,pkg:packageDraftSchema,options:z.array(z.object({id:z.string(),airline:z.string(),rate:z.number(),dates:z.array(z.string())})),updatedAt:z.number()});
type LocalDraft=z.infer<typeof draftSchema>;
const workspaceSchema=z.object({version:z.literal(1),savedAt:z.number(),tab:z.enum(['packages','categories']),query:z.string(),editor:z.enum(['packages','categories']).nullable(),editId:z.string().nullable(),drafts:z.record(draftSchema)});
function Label({title,children}:{title:string;children:React.ReactNode}){return <label className="block min-w-0 space-y-1.5 text-xs font-medium text-[#595959]"><span>{title}</span>{children}</label>}
function validImageLink(value:string){
 if(!value)return true;
 if(value.startsWith('/')&&!value.startsWith('//'))return true;
 try{return new URL(value).protocol==='https:';}catch{return false;}
}
function ImageUpload({value,alt,onChange,onBusy}:{value:string;alt:string;onChange:(url:string)=>void;onBusy:(busy:boolean)=>void}){
 const [busy,setBusy]=useState(false);
 const [previewFailed,setPreviewFailed]=useState(false);
 useEffect(()=>setPreviewFailed(false),[value]);
 const upload=async(file:File)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){toast.error('Choose a JPG, PNG or WebP image under 5 MB.');return;}const client=getSupabaseClient();if(!client)return;setBusy(true);onBusy(true);const path=`${crypto.randomUUID()}.${file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp'}`;try{const {error}=await client.storage.from('travel-images').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;onChange(client.storage.from('travel-images').getPublicUrl(path).data.publicUrl);toast.success('Image uploaded. Save the listing to use it.',{duration:2000,position:'top-center'});}catch(e){toast.error(e instanceof Error?e.message:'Image upload failed.');}finally{setBusy(false);onBusy(false);}};
 return <div className="space-y-3">
  {value&&validImageLink(value)&&!previewFailed&&<img src={value} alt={alt||'Listing preview'} onError={()=>setPreviewFailed(true)} className="h-28 w-full rounded-xl object-cover" />}
  {previewFailed&&<p role="status" className="rounded-xl bg-black/5 p-3 text-xs text-muted-foreground">Image preview unavailable. Check that the link opens a public image.</p>}
  <label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-black/25 p-3 text-xs">{busy?<Loader2 size={15} className="animate-spin"/>:<Upload size={15}/>} {busy?'Uploading…':'Upload image · JPG, PNG, WebP · max 5 MB'}<input aria-label="Upload listing image" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/></label>
  <div className="flex items-center gap-3 text-[10px] uppercase tracking-wider text-muted-foreground"><span className="h-px flex-1 bg-black/10"/>or use a link<span className="h-px flex-1 bg-black/10"/></div>
  <Label title="Image link"><input aria-label="Image link" inputMode="url" autoComplete="off" disabled={busy} maxLength={2000} value={value} onChange={e=>onChange(e.target.value.trim())} placeholder="https://example.com/image.jpg" aria-invalid={!validImageLink(value)} className={field}/></Label>
  {!validImageLink(value)&&<p role="alert" className="text-xs text-red-700">Enter a valid HTTPS image link or a local image path.</p>}
 </div>;
}
export default function AdminListings({adminId,active}:{adminId:string;active:boolean}){
 const [tab,setTab]=useState<'packages'|'categories'>('packages');const [categories,setCategories]=useState<CmsCategory[]>([]);const [packages,setPackages]=useState<CmsPackage[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [editor,setEditor]=useState<'packages'|'categories'|null>(null);const [editId,setEditId]=useState<string|null>(null);const [category,setCategory]=useState(emptyCategory);const [pkg,setPkg]=useState(emptyPackage);const [options,setOptions]=useState<FlightOption[]>([]);const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [deleting,setDeleting]=useState<{id:string;name:string;kind:'packages'|'categories'}|null>(null);
 const [ready,setReady]=useState(false);const [drafts,setDrafts]=useState<Record<string,LocalDraft>>({});const [storageError,setStorageError]=useState(false);
 const restored=useRef(false);const key=`zikhra-listings-workspace:${adminId}`;const draftKey=(kind:string,id:string|null)=>`${kind}:${id??'new'}`;
 const resume=(draft:LocalDraft)=>{setCategory(draft.category);setPkg(draft.pkg);setOptions(draft.options);setEditId(draft.id);setEditor(draft.kind);setTab(draft.kind);};
 useEffect(()=>{
  const parsed=workspaceSchema.safeParse(readAdminStorage(key));
  if(parsed.success){const value=parsed.data;setDrafts(value.drafts);setTab(value.tab);setQuery(value.query);if(value.editor){const draft=value.drafts[draftKey(value.editor,value.editId)];if(draft)resume(draft);}}
  const urlTab=new URLSearchParams(window.location.search).get('listing');if(urlTab==='packages'||urlTab==='categories')setTab(urlTab);
  setReady(true);
 },[key]);
 useEffect(()=>{
  if(!ready)return;
  let next=drafts;
  if(editor){const id=draftKey(editor,editId);const previous=drafts[id];const snapshot={kind:editor,id:editId,category,pkg,options,updatedAt:previous?.updatedAt??Date.now()};
   if(!previous||JSON.stringify({...previous,updatedAt:0})!==JSON.stringify({...snapshot,updatedAt:0})){next={...drafts,[id]:{...snapshot,updatedAt:Date.now()}};setDrafts(next);}
  }
  setStorageError(!writeAdminStorage(key,{version:1,savedAt:Date.now(),tab,query,editor,editId,drafts:next}));
 },[ready,key,tab,query,editor,editId,category,pkg,options,drafts]);
 useEffect(()=>{const restore=()=>{const value=new URLSearchParams(window.location.search).get('listing');if(value==='packages'||value==='categories')setTab(value);};window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore);},[]);
 const chooseTab=(next:'packages'|'categories')=>{setTab(next);setQuery('');const url=new URL(window.location.href);url.searchParams.set('listing',next);window.history.pushState(null,'',url);};
 const forgetDraft=(kind:'packages'|'categories',id:string|null)=>setDrafts(current=>{const next={...current};delete next[draftKey(kind,id)];return next;});
 const load=async(background=false)=>{const client=getSupabaseClient();if(!client)return;if(!background)setLoading(true);setError('');try{const [c,p]=await Promise.all([client.from('travel_categories').select('*').order('sort_order').order('name'),client.from('travel_packages').select('*').order('sort_order').order('name')]);if(c.error||p.error)throw c.error||p.error;setCategories(c.data??[]);setPackages(p.data??[]);try{sessionStorage.setItem(`zikhra-listings-cache:${adminId}`,JSON.stringify({time:Date.now(),categories:c.data??[],packages:p.data??[]}));}catch{}}catch{setError('Unable to load listings. Check your admin access or retry.');}finally{setLoading(false)}};
 useEffect(()=>{
  if(!active||restored.current)return;restored.current=true;let cached=false;
  try{const value=JSON.parse(sessionStorage.getItem(`zikhra-listings-cache:${adminId}`)||'null');if(value&&Date.now()-value.time<5*60*1000&&Array.isArray(value.categories)&&Array.isArray(value.packages)){setCategories(value.categories);setPackages(value.packages);setLoading(false);cached=true;}}catch{}
  void load(cached);
 },[active,adminId]);
 const openCategory=(item?:CmsCategory)=>{const draft=drafts[draftKey("categories",item?.id??null)];if(draft){resume(draft);return;}setEditId(item?.id??null);setCategory(item?{name:item.name,slug:item.slug,description:item.description,image_url:item.image_url,image_alt:item.image_alt,sort_order:item.sort_order,published:item.published}:{...emptyCategory});setEditor('categories');};
 const openPackage=(item?:CmsPackage)=>{const draft=drafts[draftKey("packages",item?.id??null)];if(draft){resume(draft);return;}setEditId(item?.id??null);setPkg(item?{...emptyPackage,...item,duration_days:item.duration_days??'',inclusions:item.inclusions.join('\n'),exclusions:item.exclusions.join('\n'),itinerary:item.itinerary.join('\n')}:{...emptyPackage,category_id:categories[0]?.id??''});setOptions(item?flightSchema.parse(item.options):[{id:crypto.randomUUID(),airline:'',rate:0,dates:[]}]);setEditor('packages');};
 const save=async(e:React.FormEvent)=>{e.preventDefault();const client=getSupabaseClient();if(!client)return;setBusy(true);try{
  const current=editor==='categories'?category:pkg;if((editor==='categories'&&current.slug==='all')||!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(current.slug))throw Error('Use a lowercase URL slug with letters, numbers and hyphens.');if(!current.name.trim())throw Error('A name is required.');if(!validImageLink(current.image_url))throw Error('Enter a valid HTTPS image link or upload an image.');if(current.published&&!current.image_url)throw Error('Upload a cover image before publishing.');if(current.image_url&&!current.image_alt.trim())throw Error('Add descriptive image alt text.');
  if(editor==='categories'){const payload={...category,name:category.name.trim()};const result=editId?await client.from('travel_categories').update(payload).eq('id',editId).select('id').single():await client.from('travel_categories').insert(payload).select('id').single();if(result.error)throw result.error;}
  else{const valid=flightSchema.safeParse(options);if(!valid.success)throw Error(valid.error.issues[0]?.message??'Check flight prices and dates.');if(!pkg.category_id)throw Error('Choose a category.');const lines=(s:string)=>s.split('\n').map(v=>v.trim()).filter(Boolean);if(pkg.published&&!lines(pkg.inclusions).length)throw Error('Add package inclusions before publishing.');if(pkg.published&&!categories.find(c=>c.id===pkg.category_id)?.published)throw Error('Publish the category before publishing its package.');const payload={...pkg,name:pkg.name.trim(),duration_days:pkg.duration_days===''?null:Number(pkg.duration_days),inclusions:lines(pkg.inclusions),exclusions:lines(pkg.exclusions),itinerary:lines(pkg.itinerary),options:valid.data};const result=editId?await client.from('travel_packages').update(payload).eq('id',editId).select('id').single():await client.from('travel_packages').insert(payload).select('id').single();if(result.error)throw result.error;}
  toast.success('Listing saved',{duration:2000,position:'top-center'});if(editor)forgetDraft(editor,editId);setEditor(null);await load();
 }catch(e){toast.error((e as {code?:string}).code==='23505'?'That URL slug already exists. Choose another.':(e as {message?:string}).message||'Unable to save listing.');}finally{setBusy(false)}};
 const remove=async()=>{if(!deleting)return;const client=getSupabaseClient();if(!client)return;setBusy(true);try{const result=await client.from(deleting.kind==='categories'?'travel_categories':'travel_packages').delete().eq('id',deleting.id).select('id').single();if(result.error)throw result.error;toast.success('Listing deleted',{duration:2000,position:'top-center'});forgetDraft(deleting.kind,deleting.id);setDeleting(null);await load();}catch(e){toast.error((e as {code?:string}).code==='23503'?'Move or delete packages in this category first.':(e as {message?:string}).message||'Unable to delete listing.');}finally{setBusy(false)}};
 const updateOption=(index:number,patch:Partial<FlightOption>)=>setOptions(values=>values.map((o,i)=>i===index?{...o,...patch}:o));
 const current=editor==='categories'?category:pkg;
 return <section hidden={!active} className="mx-auto max-w-6xl px-4 py-6 sm:px-6">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-medium">Listings</h2><p className="mt-1 text-xs text-muted-foreground">Manage journey categories and packages. Drafts stay private.</p></div><button onClick={()=>tab==='categories'?openCategory():openPackage()} disabled={loading||Boolean(error)||(tab==='packages'&&!categories.length)} className="flex items-center gap-2 rounded-xl bg-[#171717] px-4 py-2.5 text-sm text-white disabled:opacity-40"><Plus size={16}/>Add {tab==='categories'?'category':'package'}</button></div>
  <div className="mb-3 flex items-center justify-between text-xs text-muted-foreground"><span>Unsaved edits are kept on this device.</span><button onClick={()=>void load()} disabled={loading||busy} className="underline">Refresh listings</button></div>
  {storageError&&<p role="alert" className="mb-3 rounded-xl bg-amber-50 p-3 text-xs">Browser storage is unavailable. Keep this page open and save your edits before leaving.</p>}
  {!editor&&Object.keys(drafts).length>0&&<div className="mb-4 rounded-xl border border-black/10 bg-[#f7f5f0] p-3"><p className="mb-2 text-xs font-medium">Continue unsaved edits</p><div className="flex flex-wrap gap-2">{Object.entries(drafts).map(([id,draft])=><button key={id} onClick={()=>resume(draft)} className="rounded-lg border bg-white px-3 py-2 text-xs">{draft.kind==='categories'?draft.category.name||'New category':draft.pkg.name||'New package'}</button>)}</div></div>}
  <div className="mb-5 flex gap-1 rounded-xl bg-black/5 p-1">{(['packages','categories'] as const).map(t=><button key={t} onClick={()=>chooseTab(t)} aria-pressed={tab===t} className={`flex-1 rounded-lg py-2 text-sm capitalize ${tab===t?'bg-white shadow-sm':'text-muted-foreground'}`}>{t} ({t==='packages'?packages.length:categories.length})</button>)}</div>
  <div className="mb-4 flex items-center gap-2 rounded-xl border bg-white px-3"><Search size={16}/><input aria-label="Search listings" className="w-full bg-transparent py-3 text-sm outline-none" placeholder={`Search ${tab}`} value={query} onChange={e=>setQuery(e.target.value)}/></div>
  {loading?<p className="py-6 text-sm">Loading listings…</p>:error?<div role="alert" className="rounded-xl border p-4 text-sm">{error}<button className="ml-3 underline" onClick={()=>void load()}>Retry</button></div>:<div className="grid gap-3 md:grid-cols-2">{(tab==='categories'?categories:packages).filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).map(item=><article key={item.id} className="flex min-w-0 gap-3 rounded-2xl border border-black/10 bg-white p-3">{item.image_url?<img src={item.image_url} alt={item.image_alt} className="h-20 w-20 shrink-0 rounded-xl object-cover"/>:<div className="h-20 w-20 shrink-0 rounded-xl bg-black/5"/>}<div className="min-w-0 flex-1"><h3 className="truncate text-sm font-medium">{item.name}</h3><p className="mt-1 text-[11px] text-muted-foreground">{item.published?'Published':'Draft'}{'featured' in item&&item.featured?' · Featured':''}</p><div className="mt-3 flex gap-3"><button aria-label={`Edit ${item.name}`} onClick={()=>tab==='categories'?openCategory(item as CmsCategory):openPackage(item as CmsPackage)} className="flex items-center gap-1 text-xs"><Pencil size={13}/>Edit</button><button aria-label={`Delete ${item.name}`} onClick={()=>setDeleting({id:item.id,name:item.name,kind:tab})} className="flex items-center gap-1 text-xs text-red-700"><Trash2 size={13}/>Delete</button></div></div></article>)}{!(tab==='categories'?categories:packages).length&&<p className="p-4 text-sm text-muted-foreground">No {tab} yet. Add your first listing.</p>}</div>}
  <Dialog open={Boolean(editor)&&active} onOpenChange={open=>{if(!open&&!busy&&!uploading)setEditor(null);}}><DialogContent className="flex max-h-[90dvh] w-[calc(100%-1.5rem)] max-w-3xl flex-col overflow-hidden rounded-2xl p-0 sm:rounded-2xl"><div className="border-b p-5 pr-10"><DialogTitle>{editId?'Edit':'Add'} {editor==='categories'?'category':'package'}</DialogTitle><DialogDescription className="mt-1 text-xs">{storageError?"Save your changes before leaving.":"Edits are kept on this device until you save or discard them."}</DialogDescription></div><form onSubmit={save} className="flex min-h-0 flex-col"><div className="min-h-0 space-y-5 overflow-y-auto p-5">
   <div className="grid gap-4 sm:grid-cols-2"><Label title="Name"><input required maxLength={120} className={field} value={current.name} onChange={e=>{const next=e.target.value;editor==='categories'?setCategory({...category,name:next,slug:editId?category.slug:slugify(next)}):setPkg({...pkg,name:next,slug:editId?pkg.slug:slugify(next)});}}/></Label><Label title="URL slug"><input required className={field} value={current.slug} onChange={e=>editor==='categories'?setCategory({...category,slug:e.target.value}):setPkg({...pkg,slug:e.target.value})}/></Label></div>
   <Label title="Description"><textarea aria-label="Description" maxLength={2000} rows={2} className={field} value={current.description} onChange={e=>editor==='categories'?setCategory({...category,description:e.target.value}):setPkg({...pkg,description:e.target.value})}/></Label>
   <ImageUpload value={current.image_url} alt={current.image_alt} onBusy={setUploading} onChange={url=>editor==='categories'?setCategory(prev=>({...prev,image_url:url})):setPkg(prev=>({...prev,image_url:url}))}/>
   <Label title="Image alt text"><input maxLength={250} className={field} value={current.image_alt} onChange={e=>editor==='categories'?setCategory({...category,image_alt:e.target.value}):setPkg({...pkg,image_alt:e.target.value})}/></Label>
   {editor==='packages'&&<><div className="grid gap-4 sm:grid-cols-2"><Label title="Category"><select aria-label="Category" required className={field} value={pkg.category_id} onChange={e=>setPkg({...pkg,category_id:e.target.value})}><option value="">Choose category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}{!c.published?' (draft)':''}</option>)}</select></Label><Label title="Destinations / route"><input required className={field} value={pkg.destinations} onChange={e=>setPkg({...pkg,destinations:e.target.value})}/></Label><Label title="Departure city"><input required className={field} value={pkg.departure_city} onChange={e=>setPkg({...pkg,departure_city:e.target.value})}/></Label><Label title="Duration in days (optional)"><input type="number" min={1} max={365} className={field} value={pkg.duration_days} onChange={e=>setPkg({...pkg,duration_days:e.target.value})}/></Label><Label title="Price / room sharing basis"><input required className={field} value={pkg.sharing} onChange={e=>setPkg({...pkg,sharing:e.target.value})}/></Label></div>
   <div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-medium">Flights & departure batches</h3><button type="button" onClick={()=>setOptions([...options,{id:crypto.randomUUID(),airline:'',rate:0,dates:[]}])} className="text-xs underline">Add flight option</button></div>{options.map((o,i)=><div key={o.id} className="mb-3 space-y-3 rounded-xl border bg-[#faf9f5] p-3"><div className="flex items-center justify-between"><span className="text-xs font-medium">Option {i+1}</span><button type="button" disabled={options.length===1} onClick={()=>setOptions(options.filter((_,index)=>index!==i))} className="text-xs text-red-700 disabled:opacity-30">Remove option</button></div><div className="grid gap-3 sm:grid-cols-2"><Label title="Airline"><input required maxLength={120} className={field} value={o.airline} onChange={e=>updateOption(i,{airline:e.target.value})}/></Label><Label title="Price per adult (INR)"><input required type="number" min={1} step="0.01" className={field} value={o.rate||''} onChange={e=>updateOption(i,{rate:Number(e.target.value)})}/></Label></div><div className="space-y-2"><p className="text-xs text-muted-foreground">Departure dates</p>{o.dates.map((d,j)=><div key={j} className="flex gap-2"><input aria-label={`Option ${i+1} departure ${j+1}`} required type="date" className={field} value={d} onChange={e=>updateOption(i,{dates:o.dates.map((date,index)=>index===j?e.target.value:date)})}/><button type="button" aria-label={`Remove option ${i+1} date ${j+1}`} onClick={()=>updateOption(i,{dates:o.dates.filter((_,index)=>index!==j)})} className="p-2"><Trash2 size={14}/></button></div>)}<button type="button" className="text-xs underline" onClick={()=>updateOption(i,{dates:[...o.dates,'']})}>Add departure date</button></div></div>)}</div>
   {([{key:'hotel_details',title:'Hotels & distances'},{key:'inclusions',title:'Inclusions (one per line)'},{key:'exclusions',title:'Exclusions (one per line)'},{key:'itinerary',title:'Itinerary (one day or step per line)'},{key:'terms',title:'Booking terms & price notes'}] as const).map(item=><Label key={item.key} title={item.title}><textarea rows={3} maxLength={6000} className={field} value={pkg[item.key]} onChange={e=>setPkg({...pkg,[item.key]:e.target.value})}/></Label>)}
   <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={pkg.featured} onChange={e=>setPkg({...pkg,featured:e.target.checked})}/>Feature on homepage</label></>}
   <div className="flex flex-wrap items-end gap-4"><Label title="Display order"><input type="number" step={1} className={`${field} max-w-28`} value={current.sort_order} onChange={e=>editor==='categories'?setCategory({...category,sort_order:Number(e.target.value)}):setPkg({...pkg,sort_order:Number(e.target.value)})}/></Label><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={current.published} onChange={e=>editor==='categories'?setCategory({...category,published:e.target.checked}):setPkg({...pkg,published:e.target.checked})}/>Published</label></div>
  </div><div className="flex shrink-0 flex-wrap justify-end gap-2 border-t bg-white p-4"><button type="button" disabled={busy||uploading} onClick={()=>setEditor(null)} className="rounded-xl border px-4 py-2 text-sm">Keep draft & close</button><button type="button" disabled={busy||uploading} onClick={()=>{if(editor)forgetDraft(editor,editId);setEditor(null);}} className="px-2 py-2 text-xs text-red-700">Discard</button><button disabled={busy||uploading} className="order-first basis-full rounded-xl bg-[#171717] px-5 py-2 text-sm text-white disabled:opacity-40 sm:order-none sm:basis-auto">{busy?'Saving…':current.published?'Save & publish':'Save draft'}</button></div></form></DialogContent></Dialog>
  <Dialog open={Boolean(deleting)&&active} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><DialogContent className="w-[calc(100%-2rem)] rounded-2xl"><DialogTitle>Delete {deleting?.name}?</DialogTitle><DialogDescription>This permanently removes the listing. You can unpublish it instead to keep it as a draft.</DialogDescription><div className="flex justify-end gap-3"><button disabled={busy} onClick={()=>setDeleting(null)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button><button disabled={busy} onClick={()=>void remove()} className="rounded-xl bg-red-700 px-4 py-2 text-sm text-white">{busy?'Deleting…':'Delete'}</button></div></DialogContent></Dialog>
 </section>;
}









