"use client";
import { MapPin, ArrowUpRight } from "lucide-react";
import Link from "next/link";
import type { MarketId } from "@/lib/market-types";
import { useTravelCatalogue, flightSchema } from "@/lib/travel-cms";
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export default function FeaturedProjects({market='bangalore',featuredOnly=true,title='Featured Packages',subtitle='Choose a package and departure that suit your journey.'}:{market?:MarketId;featuredOnly?:boolean;title?:string;subtitle?:string}){
 const {packages,categories,loading,error}=useTravelCatalogue();const featured=packages.filter(p=>(!featuredOnly||p.featured)&&categories.some(c=>c.id===p.category_id));
 if(featuredOnly&&!loading&&!error&&!featured.length)return null;
 return <section className={featuredOnly?"px-5 py-14 md:px-8 md:py-16":"px-5 py-8 md:px-8 md:py-10"} aria-label={featuredOnly?"Featured packages":"Available packages"}><div className="mb-8 text-center"><p className="mb-3 font-sans text-xs uppercase tracking-[0.3em] text-gold">{featuredOnly?"Featured":"Packages"}</p><h2 className="font-serif text-3xl gold-text md:text-4xl">{title}</h2><p className="mx-auto mt-3 max-w-md text-sm leading-relaxed text-muted-foreground">{subtitle}</p></div>{loading?<p className="text-center text-sm">Loading packages…</p>:error?<p className="text-center text-sm">Packages are temporarily unavailable. Please contact us for availability.</p>:<div className="mx-auto max-w-5xl space-y-5">{!featured.length&&<p className="text-center text-sm text-muted-foreground">New packages are being planned. Contact us to discuss your dates.</p>}{featured.map(pkg=>{const options=flightSchema.parse(pkg.options);const category=categories.find(c=>c.id===pkg.category_id);return <Link key={pkg.id} href={`/${market}/packages/${pkg.slug}`} className="group block overflow-hidden rounded-xl border border-border/50 bg-card transition-colors hover:border-gold/40 md:grid md:grid-cols-2"><div className={`relative ${featuredOnly?"h-48":"h-28"} overflow-hidden md:h-full md:min-h-72`}><img src={pkg.image_url} alt={pkg.image_alt} loading="lazy" width={800} height={600} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute bottom-3 left-4 rounded-full bg-white/95 px-3 py-1 text-xs text-[#171717]">{category?.name}</span></div><div className="p-5 sm:p-6"><h3 className="mb-2 font-serif text-2xl">{pkg.name}</h3><p className="mb-4 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin size={14}/>{pkg.destinations}</p><div className="hide-scrollbar mb-3 flex gap-2 overflow-x-auto">{options.map(o=><div key={o.id} className="min-w-[145px] flex-1 shrink-0 rounded-xl border border-border/60 bg-[#f7f5f0] px-3 py-2"><p className="text-xs text-muted-foreground">{o.airline}</p><p className="mt-1 text-lg font-semibold">{money(o.rate)}</p></div>)}</div><p className="text-xs text-muted-foreground">Per adult · {pkg.sharing}</p><p className="mt-2 text-xs text-muted-foreground">{pkg.description}</p><span className="mt-4 flex items-center justify-between border-t border-border/50 pt-3 text-sm">View package & departure dates<ArrowUpRight size={17}/></span></div></Link>})}</div>}</section>;
}

