// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ejxccuheeapscdaqtbor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeGNjdWhlZWFwc2NkYXF0Ym9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MTQ3NjIsImV4cCI6MjA5MDI5MDc2Mn0.CY-E6fvYt7lUXJKRs3ANoObgWt76J0pcZ6d0PondtJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

let browserSupabase: ReturnType<typeof createClient<Database>> | null = null;

// Important: avoid initializing Supabase during SSR/prerender to prevent build-time crashes.
export function getSupabaseClient() {
  if (!isBrowser) return null;
  if (browserSupabase) return browserSupabase;

  browserSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: window.localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return browserSupabase;
}